import json
import time
import socket
import struct
import random

def load_config():
    """Load network target configuration generated by the shell script."""
    with open("config.json", "r") as f:
        return json.load(f)

def calculate_crc16_ccitt(data: bytes) -> int:
    """Calculate CRC-16-CCITT checksum based on Yamcs link specifications."""
    crc = 0x0000
    for byte in data:
        crc ^= (byte << 8)
        for _ in range(8):
            if crc & 0x8000:
                crc = (crc << 1) ^ 0x1021
            else:
                crc = crc << 1
            crc &= 0xFFFF
    return crc

def create_ccsds_packet(apid: int, sequence_count: int, packet_id: int, float_value: float) -> bytes:
    """Pack sensor data into a standard CCSDS Space Packet inherited from ccsds-default:128."""
    # Payload format according to MDB: packet-id (2-byte unsigned short) + telemetry value (4-byte float32)
    payload = struct.pack(">Hf", packet_id, float_value)

    # CCSDS Primary Header (6 bytes)
    # Packet Version (3 bits) | Packet Type (1 bit) | Secondary Header Flag (1 bit) | APID (11 bits)
    packet_id_header = (0 << 13) | (0 << 12) | (0 << 11) | (apid & 0x7FF)

    # Sequence Flags (2 bits: 3 means unsegmented) | Sequence Count (14 bits)
    packet_seq_header = (3 << 14) | (sequence_count & 0x3FFF)

    # Packet Data Length (16 bits): payload size + 2 bytes CRC - 1 (per CCSDS standards)
    packet_length = len(payload) + 2 - 1

    header = struct.pack(">HHH", packet_id_header, packet_seq_header, packet_length)

    # Calculate and append CRC-16 checksum at the end
    packet_without_crc = header + payload
    crc = calculate_crc16_ccitt(packet_without_crc)

    return packet_without_crc + struct.pack(">H", crc)

def main():
    config = load_config()
    yamcs_ip = config["yamcs_ip"]
    yamcs_port = config["yamcs_port"]
    apid = config["apid"]
    interval = config["send_interval_seconds"]

    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    print(f"📡 [Docker Device] Streaming data to Yamcs Server -> {yamcs_ip}:{yamcs_port}")

    # Sensor mapping array parsed from your Containers.csv & Parameters.csv
    sensors = [
        {"name": "SENSOR1 (PISLF)", "id": 1},
        {"name": "SENSOR2 (PISLO)", "id": 2},
        {"name": "SENSOR3 (PIGNB1)", "id": 3},
        {"name": "SENSOR4 (FISLF)", "id": 4},
        {"name": "SENSOR7 (TISLF)", "id": 7},
        {"name": "SENSOR11 (FSV2)", "id": 11}
    ]

    seq_count = 0
    try:
        while True:
            # Randomly select a sensor to simulate dynamic changes
            sensor = random.choice(sensors)
            mock_value = round(random.uniform(10.5, 95.8), 4)

            # Generate packet using APID defined in the database (default 101)
            packet = create_ccsds_packet(apid, seq_count, sensor["id"], mock_value)

            # Send packet via UDP datagram
            sock.sendto(packet, (yamcs_ip, yamcs_port))
            print(f"   [Sent] {sensor['name']} | PacketID={sensor['id']} | Value={mock_value} -> {len(packet)} bytes")

            seq_count = (seq_count + 1) % 16384
            time.sleep(interval)
    except KeyboardInterrupt:
        print("\n🛑 Simulation execution interrupted by user.")
    finally:
        sock.close()

if __name__ == "__main__":
    main()